use_auto_finetune: False
use_gpu: True
gpu_id: 0
saved_params_dir: ./output
data_dir: ./data
use_pretrained: True
checkpoint: null
save_step: 1
model: ResNet50
num_epochs: 120
image_h: 224
image_w: 224
batch_size: 8
lr: 0.01
lr_strategy: piecewise_decay
resize_short_size: 256
use_default_mean_std: False
use_distrot: True
use_rotate: True
